version = 3.3.2
runner.dialect = scala213

maxColumn = 120
align = more
align.multiline = true

indent.main = 4
indent.callSite = 4

# assumeStandardLibraryStripMargin = true
# lineEndings = preserve
# includeCurlyBraceInSelectChains = false
# danglingParentheses.preset = true

align.tokens.add = [
  {
    code = ":"
  },
  {
    code = ":="
  },
  {
    code = "="
  },
  {
    code = "//"
  },
  {
    code = "->"
  }
]


newlines.alwaysBeforeCurlyBraceLambdaParams = false
newlines.alwaysBeforeMultilineDef = false
newlines.implicitParamListModifierForce = [before]

verticalMultiline.atDefnSite = true

optIn.annotationNewlines = true
optIn.breaksInsideChains = true

rewrite.rules = [SortImports, PreferCurlyFors, AvoidInfix]
